name: gradient_app_bar
description: The official AppBar, with a more colorful twist. Add gradients to spice up your application and make it beautiful. This easy to use library makes it easy, and most of all, it is compatible with everything the normal AppBar is compatible with!
version: 0.2.0
author: Joost Lekkerkerker <joostlek@outlook.com>
homepage: https://github.com/joostlek/GradientAppBar

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=1.26.0 <3.0.0'

flutter:
  uses-material-design: true